# Generated by Django 4.0.3 on 2022-04-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cole',
            old_name='quotes',
            new_name='quote',
        ),
    ]
