# Generated by Django 4.0.3 on 2022-04-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_quotes_cole_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cole',
            options={'ordering': ['quote']},
        ),
        migrations.RemoveField(
            model_name='cole',
            name='author',
        ),
        migrations.RemoveField(
            model_name='cole',
            name='song',
        ),
    ]
